apiVersion: v1
apiUrl: https://api.hetzner.cloud/v1
authorizationType: bearerToken
resources:
  - Region
  - VirtualMachineType
  - OperatingSystemImage
  - VirtualMachine
  - SSHKey
  - Network
  - FloatingIP