server:
  port: 9002

thaalam:
  mappersPath: /Users/ashok/SpeelYaal/Technology/Workspace/thaalam/mappers
  version: 1.0.23
  providers:
    - hetzner
    - linode
    #- digitalOcean
    #- upCloud
    #- aws
    #- azure
    #- googleCloud
