server:
  port: 9002

thaalam:
  version: 1.0.23
  providers:
    - hetzner
    - digitalOcean
    - upCloud
    - linode
    - aws
    - azure
    - googleCloud
log4j2:
  status: error
  name: Log4j2Sample
  appenders: console
  appender:
    console:
      type: Console
      name: STDOUT
      layout:
        type: PatternLayout
        pattern: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  rootLogger:
    level: warn
    appenderRefs: stdout
    appenderRef:
      stdout:
        ref: STDOUT